/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javamon;

import javax.swing.JFrame;

public class App {
    public static void main(String[] args) {
        JFrame frame = new JFrame("Javamon");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setTitle("Javamon");
        frame.setSize(800, 600);
        frame.setResizable(false);
        frame.setVisible(true);
    }
}
